name: Unit Test Angular App

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        default: "['20.x']"
        description: Node.js version to use when setting up. (eg. 20.x, 18.x)

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node_version) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: npm ci

      - run: npm test -- --watch=false --browsers=ChromeHeadless
