name: Build & Publish Docker Images

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  image-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Enable Docker BuildKit
        run: |
          export DOCKER_BUILDKIT=1

      - name: Build Docker Image
        run: |
          docker build --cache-from type=local,src=/tmp/.buildx-cache \
                       --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
                       -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:latest .

      - name: Scan Docker Image for Vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:latest
          format: "github"
          output: "dependency-results.sbom.json"
          severity: "CRITICAL,HIGH"
          exit-code: "1"

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:v${{ inputs.tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:v${{ inputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:latest

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: dependency-results.sbom.json
