name: Destroy Infrastructure using Terraform

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
        default: "eu-west-2"
      TF_VERSION:
        required: true
        type: string
        default: "1.4.0"

    secrets:
        AWS_ACCESS_KEY_ID:
            required: true
        AWS_SECRET_ACCESS_KEY:
            required: true

jobs:
  cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Repository"
        uses: actions/checkout@v2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: "Set Up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.TF_VERSION }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan Destroy"
        run: terraform plan -destroy -out=tfplan-destroy

      - name: "Terraform Apply Destroy"
        run: terraform apply -auto-approve tfplan-destroy
